// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdnQhBQ19j31LgZHJQ4qlij1DOlwJL9DU',
    appId: '1:422082819859:web:1aa2ac58d9203ee8800ce6',
    messagingSenderId: '422082819859',
    projectId: 'mymusic095',
    authDomain: 'mymusic095.firebaseapp.com',
    storageBucket: 'mymusic095.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjV8ULb-wJP9ErcbZQ6FmkEP-UtPwDEIA',
    appId: '1:422082819859:android:8285caf2f0ee7d88800ce6',
    messagingSenderId: '422082819859',
    projectId: 'mymusic095',
    storageBucket: 'mymusic095.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA79sBJfS_YXYglAqN9ror7xPBekqx0YHc',
    appId: '1:422082819859:ios:be8e24527297f48d800ce6',
    messagingSenderId: '422082819859',
    projectId: 'mymusic095',
    storageBucket: 'mymusic095.firebasestorage.app',
    iosBundleId: 'com.example.myMusicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA79sBJfS_YXYglAqN9ror7xPBekqx0YHc',
    appId: '1:422082819859:ios:be8e24527297f48d800ce6',
    messagingSenderId: '422082819859',
    projectId: 'mymusic095',
    storageBucket: 'mymusic095.firebasestorage.app',
    iosBundleId: 'com.example.myMusicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdnQhBQ19j31LgZHJQ4qlij1DOlwJL9DU',
    appId: '1:422082819859:web:bed0c856198534b2800ce6',
    messagingSenderId: '422082819859',
    projectId: 'mymusic095',
    authDomain: 'mymusic095.firebaseapp.com',
    storageBucket: 'mymusic095.firebasestorage.app',
  );
}
